AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - db/*
    - bin/*
    - app/**/*/*.jbuilder
    - app/**/*/*.rabl
Rails:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Style/MutableConstant:
  Enabled: false
# Metrics/AbcSize:
#   Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
